### PR TITLE
Documentation vignette

### PR DESCRIPTION
**Pull request by xudong-Y**

### CODE REVIEW

**Review by anodaini — APPROVED** [review]
Looks good! I am curious did you use the `usethis::use_pkgdown()` and do we have a link to the 'website'?

**Comment by xudong-Y** [comment]
Thanks Asma. I'm having trouble installing the pkgdown and I need some help with it. Can you check if you can install?

**Comment by anodaini** [comment]
Oh I see,  I tried using `install.packages("pkgdown")` and I am getting this error: 
ERROR: configuration failed for package ‘ragg’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ragg’
Warning in install.packages :
  installation of package ‘ragg’ had non-zero exit status

Then I tried with `devtools::install_github("r-lib/pkgdown")` and I answered no for `Do you want to install from sources the package which needs compilation? (Yes/no/cancel)` and it seemed to work. 

However I get this error when I run `pkgdown::build_site()` : 
Error in if (pkg$bs_version == 3) { : argument is of length zero
Error: callr subprocess failed: argument is of length zero

**Comment by xudong-Y** [comment]
The `devtools::install_github("r-lib/pkgdown")` does not work for me either:(

**Pull request merged**
